import type { Metadata } from "next";
import "./globals.css";
import localFont from "next/font/local";
import { SpeedInsights } from "@vercel/speed-insights/next";
import { Analytics } from "@vercel/analytics/next";
import { Header } from "@/components/header";
import Footer from "@/components/footer";

const myFont = localFont({
  src: [
    {
      path: "../../public/fonts/TTFirsNeue-Black.ttf",
      weight: "900",
      style: "normal",
    },
    {
      path: "../../public/fonts/TTFirsNeue-Regular.ttf",
      weight: "400",
      style: "normal",
    },
    {
      path: "../../public/fonts/TTFirsNeue-ExtraBold.ttf",
      weight: "800",
      style: "normal",
    },
    {
      path: "../../public/fonts/TTFirsNeue-DemiBold.ttf",
      weight: "700",
      style: "normal",
    },
    {
      path: "../../public/fonts/TTFirsNeue-Bold.ttf",
      weight: "600",
      style: "normal",
    },
    {
      path: "../../public/fonts/TTFirsNeue-Medium.ttf",
      weight: "500",
      style: "normal",
    },
    {
      path: "../../public/fonts/TTFirsNeue-Thin.ttf",
      weight: "100",
      style: "normal",
    },
    {
      path: "../../public/fonts/TTFirsNeue-Light.ttf",
      weight: "300",
      style: "normal",
    },
  ],
  variable: "--font-custom",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={myFont.className}>
      <body className={`${myFont.variable} antialiased overflow-hidden`}>
        <header className="w-full fixed top-6 z-[99999]">
          <Header />
        </header>
        {children}
        <SpeedInsights />
        <Analytics />
        <Footer />
      </body>
    </html>
  );
}
