import "../globals.css";
import localFont from "next/font/local";
import { SpeedInsights } from "@vercel/speed-insights/next";
import { Analytics } from "@vercel/analytics/next";
import { Header } from "@/components/header";
import {
  getMessages,
  getTranslations,
  unstable_setRequestLocale,
} from "next-intl/server";
import { NextIntlClientProvider } from "next-intl";
import { locales } from "@/config";
import { ReactNode } from "react";

const myFont = localFont({
  src: [
    {
      path: "../../../public/fonts/TTFirsNeue-Black.ttf",
      weight: "900",
      style: "normal",
    },
    {
      path: "../../../public/fonts/TTFirsNeue-Regular.ttf",
      weight: "400",
      style: "normal",
    },
    {
      path: "../../../public/fonts/TTFirsNeue-ExtraBold.ttf",
      weight: "800",
      style: "normal",
    },
    {
      path: "../../../public/fonts/TTFirsNeue-DemiBold.ttf",
      weight: "700",
      style: "normal",
    },
    {
      path: "../../../public/fonts/TTFirsNeue-Bold.ttf",
      weight: "600",
      style: "normal",
    },
    {
      path: "../../../public/fonts/TTFirsNeue-Medium.ttf",
      weight: "500",
      style: "normal",
    },
    {
      path: "../../../public/fonts/TTFirsNeue-Thin.ttf",
      weight: "100",
      style: "normal",
    },
    {
      path: "../../../public/fonts/TTFirsNeue-Light.ttf",
      weight: "300",
      style: "normal",
    },
  ],
  variable: "--font-custom",
  display: "swap",
});

type Props = {
  children: ReactNode;
  params: { locale: string };
};

export function generateStaticParams() {
  return locales.map((locale) => ({ locale }));
}

export async function generateMetadata({
  params: { locale },
}: Omit<Props, "children">) {
  const t = await getTranslations({ locale, namespace: "LocaleLayout" });
  return {
    title: t("title"),
    description: "Generated by create next app",
  };
}

export default async function RootLayout({
  children,
  params: { locale },
}: Readonly<{
  children: React.ReactNode;
  params: { locale: string };
}>) {
  unstable_setRequestLocale(locale);
  const messages = await getMessages();
  return (
    <html lang={locale} className={myFont.className}>
      <body className={`${myFont.variable} antialiased overflow-hidden`}>
        <NextIntlClientProvider messages={messages}>
          <header className="w-full fixed top-6 z-[99999]">
            <Header />
          </header>
          {children}
          <SpeedInsights />
          <Analytics />
          {/* <Footer /> */}
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
